//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELITRADER_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFunil : DbContext
    {
        public BDFunil()
            : base("name=BDFunil")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANDIDATO> CANDIDATO { get; set; }
        public virtual DbSet<CANDIDATOVAGA> CANDIDATOVAGA { get; set; }
        public virtual DbSet<ETAPA> ETAPA { get; set; }
        public virtual DbSet<VAGA> VAGA { get; set; }
        public virtual DbSet<Vaga_Candidato> Vaga_Candidato { get; set; }
        public virtual DbSet<QtdCandidatosPorVaga> QtdCandidatosPorVagaSet { get; set; }
    }
}
