//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELITRADER_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga_Candidato
    {
        public string Vaga { get; set; }
        public int Código { get; set; }
        public string Candidato { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public int CodVaga { get; set; }
    }
}
